searcher:
  class: Pg
  config:
    # See http://deveiate.org/code/pg/PG/Connection.html#method-c-new
    host: ""
    port: 1000
    database: "test"

brand:
  name: "有馬"

search_schema:
  - name: uid
    type: text
    placeholder: 1234567
    jp: "ユーザーid"
  - name: type
    type: text
    placeholder: user.search
    jp: "行動タイプ"
  - name: start_at
    type: datetime-local
    jp: "開始日時(必須)"
  - name: end_at
    type: datetime-local
    jp: "終了日時(必須)"
  - name: page
    type: text
    placeholder: 1
    jp: "ページ番号"
    default_value: 1

output_schema:
  - name: time
    jp: "行動時間"
  - name: uid
    jp: "ユーザーid"
  - name: type
    jp: "行動タイプ"
  - name: other
    jp: "その他"
    hidden: true
